name: dcat
description: a simple DCAT tool
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  http: ^0.13.0
  test: ^1.15.0
  test_process: ^2.0.0
dependencies:
  args: ^2.3.0
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0  